'use strict';
const $=id=>document.getElementById(id),canvas=$('field'),ctx=canvas.getContext('2d');
document.querySelector('.legend .dot:not(.agent):not(.spent)').style.background='#cc3e3e';
let base=[],state,seed=0,selected=0,running=false,last=0,acc=0,drag=null,view={x:0,y:0,size:100},bounds={x:0,y:0,w:100},size={w:600,h:600};
const params=()=>({c:+$('strength').value,p:+$('power').value,damping:+$('damping').value,consume:$('consume').checked});
// Reference settings from the original Python simulation.
const REFERENCE={frame_skip:1,p:.3,c:10,damping:.9,dt:.1,mass:4};
// A single site's attraction, before the vector sum and velocity update.
const graphCard=document.createElement('div');
graphCard.className='force-graph';
graphCard.innerHTML=`<style>
.force-graph{margin:0 0 22px;padding:14px 10px;background:#fafbf8;border:1px solid #dfe3dc;border-radius:10px}.force-graph h3{font-size:13px;margin:0 0 9px}.force-graph p{font-size:11px;line-height:1.55;color:#67706f;margin:8px 0 0}.force-graph .equation{font:italic 25px Georgia,serif;color:#222b36;text-align:center;margin:12px 0}.force-graph .fraction{display:inline-flex;vertical-align:middle;flex-direction:column;text-align:center;font-size:23px}.force-graph .fraction span:first-child{border-bottom:1px solid #222b36;padding:0 12px 3px}.force-graph .fraction span:last-child{padding-top:3px}.force-graph details{margin:10px 0 0;padding-top:8px;font-size:11px}.force-graph svg{display:block;width:100%;height:auto;margin-top:10px}.force-graph .curve-key{display:flex;gap:12px;flex-wrap:wrap}.force-graph .curve-key span:first-child{color:#cc3e3e}.force-graph .curve-key span:last-child{color:#92998f}
</style><h3>Attraction over distance</h3><div class="equation" aria-label="f equals g times m divided by r to the power two p">f = <span class="fraction"><span>gm</span><span>r<sup>2p</sup></span></span></div><p>g: pull strength · m: point mass<br>r: distance · p: falloff</p><p id="forceEquation"></p><svg id="forcePlot" viewBox="0 0 300 220" role="img" aria-label="Attraction versus distance"></svg><p class="curve-key"><span>━━ Selected site</span><span>┄┄ Reference</span></p><p>Reference: g = 10, m = 4, p = 0.3.<br>The vertical scale adjusts to fit.</p><details><summary>Reference settings</summary><p>C (g) = 10 · P = 0.3<br>DAMPING = 0.9 · DT = 0.1<br>frame_skip = 1 (playback 1×)</p><p>The curve shows one active point’s pull. Momentum and playback affect movement, rather than this curve. A small distance cutoff keeps the simulation finite near a point.</p></details>`;
document.querySelector('#strength').closest('section').querySelector('h2').after(graphCard);
function sitePull(distance,c,weight,p){return c*weight/Math.pow(Math.max(.01,distance*distance),p);}
function drawForceGraph(){
 const site=base.find(s=>s.id===selected);if(!site)return;
 const {c,p}=params(),weight=site.weight,reference=d=>sitePull(d,REFERENCE.c,REFERENCE.mass,REFERENCE.p);
 const top=Math.max(REFERENCE.c*REFERENCE.mass,c*weight),yMax=Math.ceil(top/10)*10;
 const left=46,right=288,upper=25,bottom=180;
 const px=d=>left+(d-1)/99*(right-left),py=f=>bottom-f/yMax*(bottom-upper);
 let markup='';
 for(let i=0;i<=4;i++){const value=yMax*i/4,y=py(value);markup+=`<path d="M${left} ${y}H${right}" stroke="#e5e9e1"/><text x="${left-6}" y="${y+3}" text-anchor="end" font-size="10" fill="#67706f">${Number(value.toFixed(2))}</text>`;}
 for(const d of [1,25,50,75,100]){const x=px(d);markup+=`<text x="${x}" y="197" text-anchor="middle" font-size="10" fill="#67706f">${d}</text>`;}
 markup+=`<path d="M${left} ${upper}V${bottom}H${right}" fill="none" stroke="#92998f"/><text x="${left}" y="13" font-size="10" fill="#67706f">Pull f</text><text x="167" y="215" text-anchor="middle" font-size="10" fill="#67706f">Distance r</text>`;
 const path=fn=>Array.from({length:397},(_,i)=>{const d=1+i/4;return `${i?'L':'M'}${px(d).toFixed(2)},${py(fn(d)).toFixed(2)}`;}).join(' ');
 markup+=`<path d="${path(reference)}" fill="none" stroke="#92998f" stroke-width="1.5" stroke-dasharray="4 4"/><path d="${path(d=>sitePull(d,c,weight,p))}" fill="none" stroke="#cc3e3e" stroke-width="2.5"/>`;
 $('forcePlot').innerHTML=markup;
 $('forcePlot').setAttribute('aria-label',`Site ${site.id+1}: attraction versus distance. C ${c}, salience ${weight}, exponent ${p}. Attraction at distance 10: ${sitePull(10,c,weight,p).toFixed(2)}. Red curve compared with a fixed reference.`);
 $('forceEquation').textContent=`Site ${site.id+1}: g = ${c} · m = ${weight} · p = ${p.toFixed(2)}`;
}

function randomGenerator(n){return()=>{n|=0;n=n+0x6D2B79F5|0;let t=Math.imul(n^n>>>15,1|n);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};}
function choose(){const site=base.find(p=>p.id===selected)||base[0];selected=site.id;$('site').value=String(selected);$('weight').value=site.weight;$('weightOut').textContent=site.weight;$('selectedHint').textContent=`Site ${site.id+1} · position (${site.x.toFixed(1)}, ${site.y.toFixed(1)})`;draw();drawForceGraph();}
function menu(){$('site').replaceChildren(...base.map(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=`Site ${p.id+1}`;return o;}));choose();}
function setRunning(on){running=on;last=0;acc=0;$('run').textContent=on?'Ⅱ Pause':'▶ Run';$('status').textContent=on?'Trajectory unfolding':state.step?'Paused':'Ready to explore';}
function reset(){setRunning(false);state=Ecology.initial(base);view={x:0,y:0,size:100};stats();draw();drawForceGraph();}
function newEcology(){seed=Math.floor(Math.random()*900000)+100000;const rng=randomGenerator(seed);base=Array.from({length:+$('count').value},(_,id)=>({id,x:Math.floor(rng()*100),y:Math.floor(rng()*100),weight:1+Math.floor(rng()*9)}));selected=0;state=Ecology.initial(base);menu();reset();$('seed').textContent=seed;}
function stats(){$('time').textContent=state.t.toFixed(1);$('visited').textContent=`${state.order.length} / ${base.length}`;$('speed').textContent=Math.hypot(state.vx,state.vy).toFixed(2);$('order').textContent=state.order.length?'Encounter order: '+state.order.map(id=>`Site ${id+1}`).join(' → '):'Encounter order will appear here.';}
function fit(){const dpr=Math.min(window.devicePixelRatio||1,2);const r=canvas.getBoundingClientRect();size={w:r.width,h:r.height};canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);draw();}
function project(x,y){return [bounds.x+(x-view.x)/view.size*bounds.w,bounds.y+(1-(y-view.y)/view.size)*bounds.w];}
function unproject(x,y){return [view.x+(x-bounds.x)/bounds.w*view.size,view.y+(1-(y-bounds.y)/bounds.w)*view.size];}
function draw(){if(!state)return;const {w,h}=size;ctx.clearRect(0,0,w,h);const margin=w<450?28:38;bounds={x:margin,y:margin,w:Math.max(1,Math.min(w,h)-2*margin)};bounds.x=(w-bounds.w)/2;bounds.y=(h-bounds.w)/2;
 if(state.x<view.x||state.y<view.y||state.x>view.x+view.size||state.y>view.y+view.size){view.size*=1.5;view.x=50-view.size/2;view.y=50-view.size/2;while(state.x<view.x||state.y<view.y||state.x>view.x+view.size||state.y>view.y+view.size){view.size*=2;view.x=50-view.size/2;view.y=50-view.size/2;}}
 ctx.font='10px system-ui';ctx.fillStyle='#8a938c';ctx.strokeStyle='#edf0ea';ctx.lineWidth=1;for(let i=0;i<=5;i++){const a=bounds.w*i/5;ctx.beginPath();ctx.moveTo(bounds.x+a,bounds.y);ctx.lineTo(bounds.x+a,bounds.y+bounds.w);ctx.moveTo(bounds.x,bounds.y+a);ctx.lineTo(bounds.x+bounds.w,bounds.y+a);ctx.stroke();ctx.textAlign='center';ctx.fillText((view.x+view.size*i/5).toFixed(0),bounds.x+a,bounds.y+bounds.w+18);ctx.textAlign='right';ctx.fillText((view.y+view.size*(1-i/5)).toFixed(0),bounds.x-7,bounds.y+a+3);}
 ctx.save();ctx.beginPath();ctx.rect(bounds.x,bounds.y,bounds.w,bounds.w);ctx.clip();ctx.strokeStyle='#7765ba';ctx.lineWidth=1.8;ctx.beginPath();const stride=Math.max(1,Math.floor(state.trail.length/12000));for(let i=0;i<state.trail.length;i+=stride){const [x,y]=project(...state.trail[i]);i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.lineTo(...project(state.x,state.y));ctx.stroke();
 for(const p of state.points){const [x,y]=project(p.x,p.y),r=p.weight/view.size*bounds.w;ctx.fillStyle=p.consumed?'#a4aaa433':'#cc3e3e20';ctx.strokeStyle=p.consumed?'#a4aaa4':'#cc3e3e';ctx.lineWidth=p.id===selected?2:1;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fillStyle=p.consumed?'#a4aaa4':'#cc3e3e';ctx.fill();ctx.textAlign='left';ctx.font='11px system-ui';ctx.fillText(`${p.id+1} · ${p.weight}`,x+5,y-r-5);if(p.id===selected){ctx.setLineDash([3,3]);ctx.beginPath();ctx.arc(x,y,r+5,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}}
 const [sx,sy]=project(50,50);ctx.strokeStyle='#a79acb';ctx.lineWidth=1;ctx.beginPath();ctx.arc(sx,sy,5,0,Math.PI*2);ctx.stroke();const [x,y]=project(state.x,state.y);ctx.shadowColor='#6b58b860';ctx.shadowBlur=12;ctx.fillStyle='#6b58b8';ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.restore();
}
function animate(t){if(running){if(last)acc+=Math.min(t-last,100)* +$('pace').value/60;last=t;const n=Math.min(100,Math.floor(acc));acc-=n;for(let i=0;i<n&&state.step<50000;i++)Ecology.advance(state,params());stats();draw();if(state.step>=50000){setRunning(false);$('status').textContent='Complete · reset to explore again';}}requestAnimationFrame(animate);}
$('run').onclick=()=>{if(state.step>=50000)reset();setRunning(!running);};$('reset').onclick=reset;$('new').onclick=newEcology;
for(const [id,out,digits] of [['count','countOut',0],['strength','strengthOut',0],['damping','dampingOut',2],['power','powerOut',2],['pace','paceOut',0]]){$(id).oninput=()=>{$(out).textContent=(+$(id).value).toFixed(digits)+(id==='pace'?'×':'');if(id==='count')newEcology();else if(id!=='pace')reset();};}
$('consume').onchange=reset;$('site').onchange=()=>{selected=+$('site').value;choose();};$('weight').oninput=()=>{base.find(p=>p.id===selected).weight=+$('weight').value;reset();choose();};
canvas.onpointerdown=e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;const closest=state.points.map(p=>({p,d:Math.hypot(project(p.x,p.y)[0]-x,project(p.x,p.y)[1]-y)})).sort((a,b)=>a.d-b.d)[0];if(closest&&closest.d<Math.max(16,closest.p.weight/view.size*bounds.w+5)){selected=closest.p.id;choose();if(!running){drag=selected;canvas.setPointerCapture(e.pointerId);}}};
canvas.onpointermove=e=>{if(drag===null)return;const r=canvas.getBoundingClientRect(),[x,y]=unproject(e.clientX-r.left,e.clientY-r.top);const p=base.find(p=>p.id===drag);p.x=Math.max(0,Math.min(100,x));p.y=Math.max(0,Math.min(100,y));reset();choose();};canvas.onpointerup=()=>{drag=null;};canvas.onpointercancel=()=>{drag=null;};
function config(){return {seed,points:base,params:params(),pace:+$('pace').value};}
$('share').onclick=async()=>{const u=new URL(location.href);u.hash='experiment='+encodeURIComponent(JSON.stringify(config()));try{await navigator.clipboard.writeText(u.href);$('shareStatus').textContent='Copied. The link reopens this ecology and its settings.';}catch{$('shareStatus').textContent='Copy the address from your browser to share these settings.';location.hash=u.hash;}};
function load(){try{if(!location.hash.startsWith('#experiment='))return false;const d=JSON.parse(decodeURIComponent(location.hash.slice(12)));if(!Array.isArray(d.points)||d.points.length<1||d.points.length>25||!d.points.every(p=>Number.isFinite(p.x)&&p.x>=0&&p.x<=100&&Number.isFinite(p.y)&&p.y>=0&&p.y<=100&&Number.isInteger(p.weight)&&p.weight>=1&&p.weight<=20))return false;for(const [key,min,max] of [['c',0,50],['p',.1,1.5],['damping',0,1]])if(!Number.isFinite(d.params[key])||d.params[key]<min||d.params[key]>max)return false;base=d.points.map((p,id)=>({id,x:p.x,y:p.y,weight:p.weight}));seed=Number.isInteger(d.seed)?d.seed:0;$('count').value=base.length;$('countOut').textContent=base.length;for(const [id,key,digits] of [['strength','c',0],['power','p',2],['damping','damping',2]]){$(id).value=d.params[key];$(id+'Out').textContent=(+$(id).value).toFixed(digits);}$('consume').checked=d.params.consume!==false;$('pace').value=Number.isFinite(d.pace)?d.pace:1;$('paceOut').textContent=$('pace').value+'×';state=Ecology.initial(base);menu();reset();$('seed').textContent=seed;return true;}catch{return false;}}
if(!load())newEcology();new ResizeObserver(fit).observe(canvas.parentElement);requestAnimationFrame(animate);
